pipeline:
  clone:
    image: plugins/git
    depth: 1
  signed-off-check:
    image: python
    commands:
      - wget https://raw.githubusercontent.com/brantje/passman-ci/master/verified-check.py
      - pip install requests
      - python ./verified-check.py
    when:
      matrix:
        TESTS: signed-off-check
matrix:
  include:
    - TESTS: signed-off-check

