deploy-to-github:
  image: alpine:latest
  stage: deploy
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apk --update add openssh-client git)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  script:
    - git remote add github https://$GITHUB_TOKEN:x-oauth-basic@github.com/$REPO.git
    - git fetch github
    - git checkout github/master
    - git merge origin/master -X ours
    - git push github master
    
