deploy-to-github:
  image: alpine:latest
  stage: deploy
  only:
    - master
  before_script:
    - 'which git || ( apk --update add git)'
    - git config --global user.email "git@codehou.se"
    - git config --global user.name "codehouse-bot"

  script:
    - git remote add github https://$GITHUB_TOKEN:x-oauth-basic@github.com/$REPO.git
    - git fetch github
    - git merge github/master -X ours
    - git push github master -f
    
