deploy-to-github:
  stage: deploy
  only:
    - master
  script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh  
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - git status
  - git remote -v
  - git remote add github $REMOTE_GIT
  - git fetch github
  - git push -f origin github master
