deploy-to-github:
  stage: deploy
  only:
    - master
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh    
  - ls ~/.ssh
  
  script:
  - git status
  - git remote -v
  - git remote add github $REMOTE_GIT
  - git fetch github
  - git push -f origin github master
